Repository Bachelor2030/MCR_Game, pull requests merged in 2020-05, with the labels that each got.

#8 Refactor and move certain classes
  src/main/java/Card/Card.java
  src/main/java/Card/CardType.java
  src/main/java/Player/Player.java
  src/test/java/Card/CardTester.java
Labels: structure

#10 Setting player with tests
  README.md
  pom.xml
  src/main/java/Card/Card.java
  src/main/java/Card/CardType.java
  src/main/java/Card/CreatureCard.java
  src/main/java/Card/SpellCard.java
  src/main/java/Card/TrapCard.java
  src/main/java/Command/OnBoth.java
  src/main/java/Launcher.java
  src/main/java/ModelClasses/Receptor.java
  src/main/java/Player/Creature/Creature.java
  src/main/java/Player/Player.java
  src/test/java/Player/PlayerTester.java
Labels: documentation, enhancement

#14 Add a json file
  src/main/resources/cards.json
Labels: documentation

#15 Cards
  src/main/java/Card/Card.java
  src/main/java/Card/CardType.java
  src/main/java/Card/CreatureCard.java
  src/main/java/Card/SpellCard.java
  src/main/java/Card/TrapCard.java
  src/main/resources/cards.json
  src/test/java/Card/CardTester.java
  src/test/java/Player/PlayerTester.java
Labels: enhancement, structure

#17 Player
  src/main/java/Player/Player.java
Labels: enhancement

#19 End game merging correction
  src/main/java/Game.java
  src/main/java/ModelClasses/Receptor.java
  src/main/java/Player/Player.java
Labels: bug

#16 Commands
  src/main/java/Command/HitLiveReceptor.java
  src/main/java/Command/MoveCreature.java
  src/main/java/Command/OnBoth.java
  src/main/java/Command/OnCreature.java
  src/main/java/Command/OnPlayer.java
  src/main/java/ModelClasses/LiveReceptor.java
  src/main/java/ModelClasses/Receptor.java
  src/main/java/Player/Creature/Creature.java
  src/main/java/Player/Player.java
Labels: enhancement

#18 Add a GameCreator class
  pom.xml
  src/main/java/GameCreator.java
  src/main/java/Launcher.java
  src/main/java/ModelClasses/Client.java
  src/main/java/Utils/CardsJsonParser.java
  src/main/resources/cards.json
Labels: enhancement, structure

#21 Command in cards
  README.md
  src/main/java/Card/Card.java
  src/main/java/Card/CardType.java
  src/main/java/Command/Commands/CreateCreature.java
  src/main/java/Command/Commands/CreateTrap.java
  src/main/java/Command/Commands/GetCardFromDiscard.java
  src/main/java/Command/Commands/HitLiveReceptor.java
  src/main/java/Command/Commands/MoveCreature.java
  src/main/java/Command/Macro.java
  src/main/java/Game.java
  src/main/java/Receptors/Creature/Creature.java
  src/main/java/Receptors/Player.java
  src/main/java/Receptors/Trap.java
  src/test/java/Command/CommandTester.java
  src/test/java/Receptors/Creature/CreatureTester.java
  src/test/java/Receptors/PlayerTester.java
Labels: enhancement

#22 Fb gui
  src/main/java/GameBoard/Board.java
  src/main/java/Launcher.java
  src/main/java/View/GameBoard.java
  src/main/java/View/GamePanel.java
Labels: enhancement, structure

#24 mise en place de sprites
  ch.heigvd.mcr.projet.iml
  src/main/java/GameBoard/Board.java
  src/main/java/GameBoard/Line.java
  src/main/java/GameBoard/Spot.java
  src/main/java/GameBoard/island.png
  src/main/java/GameCreator.java
  src/main/java/Launcher.java
  src/main/java/Maths/Matrix.java
  src/main/java/Maths/Vector2f.java
  src/main/java/Utils/CardsJsonParser.java
  src/main/java/View/GameBoard.java
  src/main/java/View/GamePanel.java
  src/main/java/View/Graphics/BufferedImageLoader.java
  src/main/java/View/Graphics/Font.java
  src/main/java/View/Graphics/Sprite.java
  src/main/java/View/Graphics/SpriteSheet.java
  src/main/java/View/linkformatted.png
  src/test/java/Command/CommandTester.java
  src/test/java/GameBoard/BoardTester.java
  src/test/java/GameBoard/LineTester.java
  src/test/java/GameBoard/SpotTester.java
  src/test/java/Receptors/PlayerTester.java
Labels: enhancement

#27 Add the Egg class
  src/main/java/Game/Game.java
  src/main/java/Game/Utils/GameCreator.java
  src/main/java/ModelClasses/LiveReceptor.java
  src/main/java/ModelClasses/Receptor.java
  src/main/java/ModelClasses/Receptors/Egg.java
  src/main/java/ModelClasses/Receptors/Player.java
  src/main/java/Utils/CardsJsonParser.java
  src/test/java/Receptors/PlayerTester.java
Labels: enhancement, structure

#31 Add the egg tester -_-'
  src/test/java/Receptors/EggTester.java
Labels: bug, enhancement

#32 Add the uml
  src/main/resources/uml_12mai2020.png
Labels: documentation

#33 Add commands
  src/main/java/Game/GameBoard/Line.java
  src/main/java/Game/GameBoard/Spot.java
  src/main/java/ModelClasses/Receptors/Chest.java
  src/main/java/ModelClasses/Receptors/Creature/Creature.java
  src/main/java/ModelClasses/Receptors/Player.java
  src/test/java/Game/LineTester.java
  src/test/java/Game/SpotTester.java
  src/test/java/ModelClasses/CommandTester.java
  src/test/java/Receptors/ChestTester.java
  src/test/java/Receptors/PlayerTester.java
Labels: enhancement

#34 Change creature position from Spot to Position
  src/main/java/Game/GameBoard/Position.java
  src/main/java/Game/GameBoard/Spot.java
  src/main/java/ModelClasses/Commands/CreateCreature.java
  src/main/java/ModelClasses/Commands/CreateTrap.java
  src/main/java/ModelClasses/Receptors/Creature/Creature.java
  src/main/java/ModelClasses/Receptors/Trap.java
  src/test/java/ModelClasses/CommandTester.java
Labels: enhancement, structure
